# Generated by Django 6.0.3 on 2026-03-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
    ]
