# Generated by Django 6.0.3 on 2026-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0003_remove_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
