# Generated by Django 6.0.3 on 2026-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0005_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=1),
        ),
    ]
